### ISSUE TITLE
MoreCollectors.toImmutableMultiset collector broken (runtime crashes!!)

### ISSUE THREAD

**Issue by Tarrasch** [yanaga/guava-stream#2]
I'm not able to add a reproduce-able testcase. Sorry.

However I experience that 

```
 .collect(MoreCollectors.toImmutableMultiset());
```

doesn't work but

```
.collect(Collectors.collectingAndThen(Collectors.toList(), ImmutableMultiset::copyOf))
```

works.

---

I  have not debugged this too much, but I believe that we tell [(source)](https://github.com/yanaga/guava-stream/blob/48e0b3d6d3eb47d12e8ffcbe5523243c3160c0d9/src/main/java/me/yanaga/guava/stream/MoreCollectors.java#L172) the Stream API that our collector is able to handle the `CONCURRENT` attribute.  I'm not sure at all about this, but I suspect that it's not true that the `ImmutableMultiset.Builder` class is thread-safe as `CONCURRENT`  would suggest.

**Comment by cowwoc** [comment]
@Tarrasch Which version are you using? Please provide the full stack-trace or error message you see. You can also try my library at https://bitbucket.org/cowwoc/guava-jdk8/ if you are unable to get the problem resolved with this library.

**Comment by Tarrasch** [comment]
Thanks for your quick reply! I didn't know if this repo was still maintained or not. I'll try to see if I can get something reproducible tomorrow!

By the way, is guava-jdk8 a superset of this repo basically?

**Comment by cowwoc** [comment]
@Tarrasch The two projects are unrelated. I started my own project because I wanted to try a different syntax for building collectors.

**Comment by Tarrasch** [comment]
Ok, here's a trivial testcase to reproduce the bug:

``` java
    public static void main(String[] args) {
        List<String> nCopies = Collections.nCopies(100000, "hello");
        ImmutableMultiset<String> ims = nCopies.parallelStream().collect(MoreCollectors.toImmutableMultiset());
        System.out.println(ims.size());
    }
```

This produced the output `97629` for me. Obviously it should print out `100000` which it will do if I use `stream()` instead of `parallelStream()`.

Edit: I use version 1.0, using the README's gradle line `compile "me.yanaga:guava-stream:1.0`

**Comment by Tarrasch** [comment]
@cowwoc, I changed dependency to `guava-jdk8` (the one made by you) and the bug is now gone! Thanks. For anyone looking, here it is on [mvn repository](https://mvnrepository.com/artifact/org.bitbucket.cowwoc/guava-jdk8/2.0.0)

**Comment by cowwoc** [comment]
@Tarrasch Cool. Glad I could help!
